name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.7.0
  http: ^1.2.0   # for weather API requests
  image_picker: ^0.8.7+4
  path_provider: ^2.0.15
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/time_capsule.svg
